services:
  app:
    build:
      context: .
      target: app
    depends_on:
      ollama:
        condition: service_started
    init: true
    restart: always
    ports:
      - 8000:8000
    environment:
      - DEFAULT_STORAGE_DIR
      - OLLAMA_URL
    volumes:
      - ./tmp:/pdfs

  ollama:
    image: ollama/ollama
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama:rw
      - ./models:/models
