services:
  app:
    build:
      context: .
      target: development
    init: true

  ollama:
    image: ollama/ollama
    restart: always
    ports:
      - 11434:11434
    volumes:
      - ./ollama:/root/.ollama:rw
      - ./models:/models
